# Generated by Django 2.0.4 on 2019-05-16 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_category_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
